name: "Release Service"

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: windows
            arch: amd64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64

    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1.52
        with:
          project_path: ./pkg/service
          binary_name: service
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.os }}
          goarch: ${{ matrix.arch }}
          compress_assets: FALSE
          md5sum: FALSE
